### ISSUE TITLE
issue on textsstyle extension

### ISSUE THREAD

**Issue by SedAmigo** [TechieBlossom/movie_app_tutorial#14]
hello sir ...first or all thank you for this amazing tutorial
my problem is I'm having problem with extension for subtitle1,,,for royal blue color

**Comment by PrateekSharma1712** [comment]
What is tha issue?

**Comment by sairanjit** [comment]
![image](https://user-images.githubusercontent.com/34263716/100477234-c0910f00-310d-11eb-8c66-80bff19d3b81.png)
I am getting an error as => The getter 'sp' isn't defined for the type 'double'.

**Comment by PrateekSharma1712** [comment]
It seems you haven't imported the extension in this file.

Please add an import statement

**Comment by sairanjit** [comment]
Its working now i missed a import statement

> It seems you haven't imported the extension in this file.
> 
> Please add an import statement

**Comment by sairanjit** [comment]
> It seems you haven't imported the extension in this file.
> 
> Please add an import statement

oh Got it I missed the import statement working now thanks

**Comment by validity-check** [comment]
Someone should close this issue.
