### ISSUE TITLE
BEST APPROACH WHEN INPUTTING DATA IN REPOSITORY

### ISSUE THREAD

**Issue by Devlonoah** [TechieBlossom/movie_app_tutorial#28]
**WHICH OF THESE IS RECOMMENDED **

No 1.... (Inputting data as a model)
`abstract class NoteRepository {
  Future<Either<AppFailure, List<NoteEntity>>> fetchAllNote();
  Future addNote(NoteEntity note);
  Future updateNote(NoteEntity note);
  Future deleteNote(NoteEntity note);
}`

or
No2.... (Inputting data as a data type or separately😊)

`abstract class NoteRepository {
  Future<Either<AppFailure, List<NoteEntity>>> fetchAllNote();
  Future addNote({int id,String noteTitle,String note);
  Future updateNote({int id,String noteTitle,String note});
  Future deleteNote({int id,String noteTitle,String note});
}`

During the course of adding parameters should the parameters be a model or inputted separately

For Example
While trying to add new note in the app
Should approach  No1 be used or No2

**Comment by TechieBlossom** [comment]
No1. It is more maintainable.
