### ISSUE TITLE
mapEventToState has been deprecated

### ISSUE THREAD

**Issue by GoncaloR19** [TechieBlossom/movie_app_tutorial#34]
Hello Sir. Prateek Sharma,

Thanks so much for this awesome tutorial, first all.
After following your tutorial, I found out that the _mapEventToState_ method has been **deprecated** due to the _flutter_bloc_ package update to version ^8.
If you could update your code to the latest version, that would be greatly appreciated. Alternatively, if possible, create a new tutorial using this example (with the latest version of the flutter_bloc package).

In order to get to my problem: https://youtu.be/-FNmRWtP_ek?list=PL342JVRNQxEAcQdnNeN0JmMzfcm6VtLxS (min 12:35)

**Comment by TechieBlossom** [comment]
@GoncaloR19 In-depth Bloc Series
https://www.youtube.com/playlist?list=PL342JVRNQxEBRlMdvCEBI_p3lg0wLpt2C

This series is with bloc 8. Can you refer this?
